version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
  bootstrapping:
    image: demo
    build: .
    ports:
      - "8086:8096"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://subashnatrayan28:<C0JizQqizMtw9ie0>@mentorbridge.qmme5go.mongodb.net/?retryWrites=true&w=majority&appName=MentorBridge
    depends_on:
      - mongodb
