version: '3.8'
services:
  app:
    image: thunderscotch23/demo:${BUILD_NUMBER}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  demo-project:
    image: demo
    build: .
    ports:
      - "8086:8086"

  bootstrapping:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    depends_on:
      - demo-project
