version: '3.8'
services:
  app:
    image: thunderscotch23/demo:${BUILD_NUMBER}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
  bootstrapping:
    image: demo
    build: .
    ports:
      - "8086:8096"
    depends_on:
      - mongodb
