version: '3.8'
services:
  app:
    image: thunderscotch23/demo:${BUILD_NUMBER}
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - monitoring

  bootstrapping:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge